version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL=http://localhost:8000/
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - git-crm-front-network

networks:
  git-crm-front-network:
    driver: bridge 