version: '3.8'

services:
  # Backend service
  api:
    build:
      context: ./git-crm-back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - git-crm-network

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - git-crm-network

  # Frontend service
  web:
    build:
      context: ./git-crm-front
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL=http://localhost:8000/
    volumes:
      - ./git-crm-front:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - api
    networks:
      - git-crm-network

networks:
  git-crm-network:
    driver: bridge

volumes:
  mongodb_data:
  frontend_node_modules: 