version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - git-crm-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - git-crm-network

networks:
  git-crm-network:
    driver: bridge

volumes:
  mongodb_data:
  node_modules: 